name: Test Application
on:
  push:
jobs:
  Test-Application:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Tests for Applications"
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true
      - run: npm install
      - run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - run: npm run lint
